### ISSUE TITLE
Update bundled go-ipfs version for existing CLI install

### ISSUE THREAD

**Issue by walkah** [fission-codes/fission#600]
The CLI fetches a version of go-ipfs during `fission setup` ... however, we don't check or update the bundled go-ipfs at other times. This means that even if you update the CLI version, it will use the go-ipfs version from the initial setup.

We already do a periodic check for the CLI version - I propose we check the current `go-ipfs` version on the same cycle (and potentially update).

Workaround: running `fission setup` will download the version to match.

**Comment by therealjeffg** [comment]
With the new server implementation this should not be necessary.
