### ISSUE TITLE
Add support for an Ethereum PK elliptic curve

### ISSUE THREAD

**Issue by walkah** [fission-codes/fission#626]
In support of https://github.com/fission-suite/webnative-walletauth/issues/1 : Need to modify the database / REST api to support additional key types.

> Either add support for did:pkh or did:key:SECP_KEY. The PKH key might not be possible, or require a lot of changes, since you'll always need an accompanied UCAN (or other signed item) to get the signature from (because we need the signature to get the public key from the ethereum address in the PKH DID).

**Comment by icidasset** [comment]
https://github.com/fission-codes/fission/pull/625
